theme: jekyll-theme-leap-day
title:            pySTEPS
description:      the nowcasting initiative
disqus_shortname: pysteps

github:
  repository_url: https://github.com/pySTEPS

# Links to include in top navigation
# For external links add external: true
links:
  - title: Quick-start guide
    url: /quick-start
  - title: Github repository
    url: https://github.com/pySTEPS 
    external: true
