theme:            jekyll-theme-leap-day
title:            pySTEPS
description:      the nowcasting initiative
show_downloads: true
github:
  repository_url: https://github.com/pySTEPS/pysteps
  zip_url: https://github.com/pySTEPS/pysteps/archive/v1.0.0.zip
  tar_url: https://github.com/pySTEPS/pysteps/archive/v1.0.0.tar.gz  
# Google Analytics ID
google_analytics: "UA-122857614-1" 
